version: '3'
services:
  master-mysql:
    container_name: master-mysql
    build:
      context: ./build/
      dockerfile: mysqlMasterDockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - master-data:/var/lib/mysql
      - ./db_init/master:/docker-entrypoint-initdb.d
  slave-mysql:
    container_name: slave-mysql
    build:
      context: ./build/
      dockerfile: mysqlSlaveDockerfile
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - slave-data:/var/lib/mysql
      - ./db_init/slave:/docker-entrypoint-initdb.d

volumes:
  master-data:
  slave-data:
